### ISSUE TITLE
Provide warning output when certain portions of the Inspec control cannot be filled out

### ISSUE THREAD

**Issue by Bialogs** [mitre/inspec_tools#128]
When converting CIS XLSX to Inspec, there are oftentimes when the spreadsheet is not 100% complete. We detect this with nil and empty checks, but should report via STDOUT a message to the user that these fields are empty due to input format.

**Comment by Bialogs** [comment]
We can do this in

https://github.com/mitre/inspec_tools/blob/586b0f6f25c9199d62bdc8d125a7b57ca9f4c889/lib/inspec_tools/inspec.rb#L300-L302

when the `.nil?` case is true.

**Comment by aaronlippold** [comment]
Given @camdenmoors latest work, this could be a good issue for him?

**Comment by camdenmoors** [comment]
*2InSpec on the SAF CLI will now warn you if fields are missing but have a mapping
