### ISSUE TITLE
Support for new group and rule ids

### ISSUE THREAD

**Issue by Bialogs** [mitre/inspec_tools#135]
Given a DISA xccdf with new format we should be able to continue to create inspec profiles.

Reference: https://public.cyber.mil/announcement/disa-posts-files-to-test-new-stig-group-and-rule-ids/

**Comment by rx294** [comment]
Please bring in new legacy fields found here 
```
    <ident system="http://cyber.mil/legacy">SV-86473</ident>
    <ident system="http://cyber.mil/legacy">V-71849</ident>
```
as `legacy_gid` and `legacy_rid`
