### ISSUE TITLE
Allow for allow for three new types of desc: justification, caveat, *_discussion

### ISSUE THREAD

**Issue by Bialogs** [mitre/inspec_tools#137]
These fields need to be parsed and set appropriately on creation of controls

Where applicable the caveat, justification, `*_discussion` are appended to the 'Finding Details' on output

**Comment by aaronlippold** [comment]
#171

**Comment by camdenmoors** [comment]
Desc fields are now dynamic and set inside of your mapping files with *2inspec on the SAF CLI
