### ISSUE TITLE
Enhance compliance and summary and the threshold.yml to define the expected status of a control or controls and create a baseline of status, counts from an existing results file

### ISSUE THREAD

**Issue by aaronlippold** [mitre/inspec_tools#142]
The use case is I have a pr for a control and it went from failed to passed or error to pass or skipped...

Secondary use case I want to be able to process a result file as a ‘base’ status list grouped in the pass fail na ... bucks so that as we push a pr we update the threshold file for the control we fixed and it’s new status. 

Cli flag support may also be useful where we pass the expected status of a control.

**Comment by aaronlippold** [comment]
@rbclark @Bialogs @rx294 given the work we did with --json-summary is this a short walk. Having this ability to have compliance grok the expected status - pass, failed, NA, Skipped,Error - will help us close the loop on automated CI/CD driven gold disk creation.

**Comment by camdenmoors** [comment]
Added in `saf generate:threshold` of the SAF CLI
