### ISSUE TITLE
Create a generic JSON import method for InSpec JSONs.

### ISSUE THREAD

**Issue by rbclark** [mitre/inspec_tools#165]
Currently we parse the InSpec JSON differently depending on if we are generating a XCCDF output

https://github.com/mitre/inspec_tools/blob/bd2c1adb6618c5324871d798d1b4b36765c2d892/lib/utilities/inspec_util.rb#L49-L54

or a CKL output

https://github.com/mitre/inspec_tools/blob/bd2c1adb6618c5324871d798d1b4b36765c2d892/lib/utilities/inspec_util.rb#L88-L93

Instead of ingesting our data differently depending on the output, we should instead parse the inspec JSON in a single manner and then map it to an internal class that we create, and create helper output methods on that object type. This will mean that changes to the Inspec JSON schema will only have to be updated in 1 place, and methods like summary will no longer break if an output format changes (see #164)

**Comment by camdenmoors** [comment]
This is now part of hdf-converters and uses the base converter
