### ISSUE TITLE
All Impacts Parsed from PDF are Medium

### ISSUE THREAD

**Issue by Bialogs** [mitre/inspec_tools#173]
https://github.com/mitre/inspec_tools/blob/cea543d73d32a299e81a02398869feaca862d9bb/lib/inspec_tools/pdf.rb#L66

Why? Should this be the case?

**Comment by aaronlippold** [comment]
- [ ] CIS Level 1 controls should be low
- [ ] CIS Level 2 conrols should be medium
- [ ] CIS Level 3 controls should be high
- [ ] add unit and functional tests
- [ ] Document in the README for this converter the standard patter of conversion

**Comment by Bialogs** [comment]
According to @ejaronne this is valid.
