### ISSUE TITLE
inspec_tools docker container doesn't let me go into a bash shell

### ISSUE THREAD

**Issue by aaronlippold** [mitre/inspec_tools#184]
➜  ~ docker run -it -v$(pwd):/share mitre/inspec_tools /bin/bash

Can't find bin/bash

**Comment by rbclark** [comment]
This is as designed, you are supposed to use it as if it were an inspec binary.

Because of this, the entrypoint of the container is `inspec_tools`, and not bash. This means that if you want to drop into a bash shell you have to add `--entrypoint /bin/bash` to the middle of your docker command.
