### ISSUE TITLE
Create a generic import method for all *2inspec methods

### ISSUE THREAD

**Issue by rbclark** [mitre/inspec_tools#188]
Currently we handle `pdf2inspec`, `xccdf2inspec`, `csv2inspec`, and `xls2inspec` all differently. We should create an intermediate ruby object that all of these models convert to, which can potentially be the same object as #165. All of the exporters should then check to verify that the required methods are filled out on the object.

This is the same idea as https://github.com/mitre/inspec_tools/issues/165 just with `*2inspec` instead of `inspec2*`.

**Comment by camdenmoors** [comment]
This is now part of the SAF CLI
