### ISSUE TITLE
CSV2Inspec Parse out Extra CCI information

### ISSUE THREAD

**Issue by Bialogs** [mitre/inspec_tools#200]
When using a CSV generated by STIG viewer the viewer throws a bunch of extra information in the CCI# column that should get dropped when creating the Inspec Profile.

**Comment by aaronlippold** [comment]
Also, there are cases where there are multiple CCIs associated with a
control so we should have a kind of loops I would guess. Converting the
RHEL XCCDF should provide an example of this
--------
Aaron Lippold

lippold@gmail.com

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'
