### ISSUE TITLE
inspec2ckl does not create a title that matches original XCCDF document

### ISSUE THREAD

**Issue by b-mad** [mitre/inspec_tools#213]
When an XCCDF is used to generate a Checklist in STIGViewer the title output is different than when inspec2ckl is used to create the checklist title. An XCCDF attributes input is needed to allow for consistency with STIGViewer behavior.

The proposal here is to expose attributes in the same way as inspec2xccdf so that a matching title may be made in artifact creation.

https://github.com/mitre/inspec_tools/blob/2862786fedefec4d488106bba8a9b580b95c74a6/lib/inspec_tools/plugin_cli.rb#L58-L59

Updating inspec.rb with the following can then complete the update.

```ruby
    def generate_title(attributes, json)
      return "#{attributes['benchmark.title']} :: Version #{attributes['benchmark.version']}, #{attributes['benchmark.plaintext']}" if attributes['benchmark.title']
```

**Comment by aaronlippold** [comment]
Looking forward to the PR. Please fork the repo and create a PR so it will
trigger the unit and ci/cd test suite so we can do a peer review and merge.
Thanks.
--------
Aaron Lippold

lippold@gmail.com

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'
