### ISSUE TITLE
Threshold does not seem to respect 'error' value and only validates percentage.

### ISSUE THREAD

**Issue by aaronlippold** [mitre/inspec_tools#244]
see build https://github.com/mitre/microsoft-edge-stig-baseline/actions/runs/1203403063 for an example

**Comment by aaronlippold** [comment]
If you look at the threshold file, it is defined to not have any errors but the CICD passed

**Comment by Bialogs** [comment]
Your threshold file does not define errors correctly. You need to set `errors.total.max: 0`
