### ISSUE TITLE
add "# encoding: utf-8" to controls

### ISSUE THREAD

**Issue by ejaronne** [mitre/inspec_tools#54]
# encoding: utf-8

should be added to the top of all controls for "2inspec" tools.

**Comment by TheLonelyGhost** [comment]
Is this still necessary with modern versions of ruby? Seems this is an artifact of Ruby 1.x in order to support built-in UTF-8 characters, which is EOL'ed.

https://bugs.ruby-lang.org/issues/6679

**Comment by aaronlippold** [comment]
The challenge we are addressing is windows zip files of the profiles. We have had issues if the encoding isn't in the files for some reason. Is there a better fix?

**Comment by TheLonelyGhost** [comment]
Honestly I haven't experienced the windows zip file problems of which you speak, so I can't say that I know of a better fix.

Thanks for the additional context though!
