### ISSUE TITLE
Prompt for mapping files if not provided via command line flag.

### ISSUE THREAD

**Issue by aaronlippold** [mitre/inspec_tools#56]
Consider using the `tty-prompt` Gem to ask users for the required information.

**Comment by Bialogs** [comment]
Consider changing everywhere we currently use `ask()` to be the `tty-prompt`

**Comment by Bialogs** [comment]
#204 Sets the foundation with breaking generate_mapping out into its own class.

**Comment by aaronlippold** [comment]
This is connected to the work you are currently doing with metadata @Bialogs

**Comment by aaronlippold** [comment]
#246

**Comment by camdenmoors** [comment]
Implemented in the SAF CLI (errors if no mapping or template is passed)
