### ISSUE TITLE
Request converter from InSpec profile to NIST OSCAL Format

### ISSUE THREAD

**Issue by ejaronne** [mitre/inspec_tools#59]

**Comment by aaronlippold** [comment]
Given @rbclark work on the ORION project, we may have a better idea of what this request is and if it makes sence. Please discuss.

**Comment by tohch4** [comment]
I helped @rbclark with the [inspec-oscal plugin](https://github.com/mitre/inspec-oscal) and I am willing to chip in. Let me know how you can help

**Comment by camdenmoors** [comment]
Duplicate of https://github.com/mitre/heimdall2/issues/2403
