### ISSUE TITLE
Fix VERSION file update to update the right file in the gem

### ISSUE THREAD

**Issue by aaronlippold** [mitre/inspec_tools#79]
The standard location for the version information is /lib/<tool>/version.rb in a gem. There should be semantic versioning gems we can use. The VERSION file ( not a `.md` file ) should just be a string with the current version in it - aka `1.6.5` in this case. 

I think the current `version.md` the file would be better named `release.md`

**Comment by lukemalinowski** [comment]
I dont see a version.md file, just so you know.

**Comment by djhaynes** [comment]
VERSION.md was changed to RELEASE.md, but, Aaron is referring to lib/inspec_tools/version.rb in this issue.

**Comment by aaronlippold** [comment]
I think it is in the root directory
--------
Aaron Lippold

lippold@gmail.com

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'

**Comment by Bialogs** [comment]
The version.yml GitHub action we have actually updates the correct file, but it does not seem to be working correctly within the runner.
