### ISSUE TITLE
Support inclusion of Inspec test results in the XCCDF output

### ISSUE THREAD

**Issue by b-mad** [mitre/inspec_tools#91]
This introduces the ability to take Inspec test results and write them to the XCCDF file produced in the command inspec2xccdf. The resulting file may then be used for any downstream data conversion or rendering.

The result of this will provided the following.

* Add test result data into produced XCCDF XML fully complying with the XCCDF 1.1 specification
* Address current bugs that result in non-conformant XCCDF
* Address bug where XCCDF to Inspec produces a rule fix_id and the Inspec to XCCDF reads fix_ref.
* Add XCCDF 1.1 XSD validation tests
* Add HappyMapper objects for TestResult translation.
* Add test formatter and Rake task to exclude slow running tests

**Comment by b-mad** [comment]
I plan to submit a pull request that implements this enhancement.

**Comment by Bialogs** [comment]
Are you talking about XCCDF Results XML file or a DISA Checklist XML file? If you're talking about DISA checklists we already have `inspec2ckl`.

Happy to review any patches.

**Comment by Bialogs** [comment]
Also as a note we would like to support the 1.2 edition.

Reference : https://csrc.nist.gov/Projects/Security-Content-Automation-Protocol/Specifications/xccdf

**Comment by b-mad** [comment]
I am talking about producing  and XCCDF Results XML file that has the results or the Inspec tests in the conformant format.
